name: portfolio-manager-rust

services:
  db:
    container_name: portfolio-manager-rust_db
    image: postgres:17.5
    restart: on-failure:3
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-portfolio_manager}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      POSTGRES_DB: ${POSTGRES_DB:-portfolio_manager}
    volumes:
      - ./data/db:/var/lib/postgresql/data:Z
    ports:
      - ${DB_PORT:-5432}:5432

  redis:
    container_name: portfolio-manager-rust_redis
    image: redis:8.2
    restart: on-failure:3
    environment:
      - REDIS_REQUIREPASS=${REDIS_REQUIREPASS:-password}
    volumes:
      - ./data/redis:/data
    command:
      - /bin/sh
      - -c
      - redis-server --requirepass "$${REDIS_REQUIREPASS}"

  mongo:
    container_name: portfolio-manager-rust_mongo
    image: mongo:7.0
    restart: on-failure:3
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME:-portfolio_manager}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_USERNAME:-password}
    volumes:
      - ./data/mongo:/data/db

  mongo-express:
    container_name: portfolio-manager-rust_mongo-express
    image: mongo-express
    restart: always
    ports:
      - ${ME_PORT:-8081}:8081
    depends_on:
    - mongo
    environment:
      ME_CONFIG_MONGODB_URL: ${ME_CONFIG_MONGODB_URL:-mongodb://portfolio_manager:password@mongo:27017/}
      ME_CONFIG_BASICAUTH: false

  rust:
    container_name: portfolio-manager-rust_rust
    image: rust
    restart: on-failure:3
    depends_on:
    - db
    - redis
    - mongo
    volumes:
      - ./backend:/app
    ports:
      - ${RUST_PORT:-3000}:3000
    working_dir: /app
    command: >
      sh -c "cargo run --bin migrate --no-default-features --features migrate &&
        cargo run --bin portfolio_manager"

  angular:
    container_name: portfolio-manager-rust_angular
    build:
      context: docker/angular
    image: dev-angular
    restart: on-failure:3
    depends_on:
    - rust
    volumes:
      - ./frontend:/app
    ports:
      - ${ANGULAR_PORT:-4200}:4200
    working_dir: /app
    command: ng serve --host 0.0.0.0
